### ISSUE TITLE
Any way to support multiple worksheets?

### ISSUE THREAD

**Issue by mangvlad** [nunukim/node-xlsx-stream#1]
I am looking to use this module but have a requirement to create multiple worksheets.

Thanks!

**Comment by nunukim** [comment]
Thanks for your interest.

Currently, no. But I'm planning to add a new method to do that.

**Comment by mangvlad** [comment]
Do you have any time estimates for when you may have it? 
Also, it seems that the zip module you are using no longer works (since v 0.10 of node...) 
Looks like the new (replacement) library for zip is now https://github.com/ctalkington/node-archiver

Any way I can help with adding this functionality?

**Comment by nunukim** [comment]
> Do you have any time estimates for when you may have it? 

I've just done that.

> Also, it seems that the zip module you are using no longer works (since v 0.10 of node...) 
> Looks like the new (replacement) library for zip is now https://github.com/ctalkington/node-archiver

Thank you for teaching.
I switched library to node-archiver and now it passes the test also in v0.10 .
